export const appStrings = {
  brandName: 'TitanLog',
  slogan: 'Train. Track. Transform.',
  common: {
    goBack: 'Geri dön',
    apply: 'Uygula',
    cancel: 'Vazgeç',
    decrease: 'Azalt',
    increase: 'Artır',
    inlineWheelHint:
      'Aşağı kaydırarak artır, yukarı kaydırarak azalt; yazmak için dokun.',
    manualEntry: 'Elle Gir',
    useWheel: 'Çarkı Kullan',
    wheelHint: 'Aşağı çevirerek artır, yukarı çevirerek azalt.',
  },
  database: {
    loadingTitle: 'Antrenman alanın hazırlanıyor',
    loadingDescription: 'Yerel verilerin güvenli biçimde hazırlanıyor.',
    errorTitle: 'Antrenman verilerine ulaşılamadı',
    errorDescription:
      'Yerel veriler hazırlanırken bir sorun oluştu. Tekrar deneyebilirsin.',
    retry: 'Tekrar Dene',
  },
  auth: {
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    signInDescription: 'TitanLog hesabına erişmek için bilgilerini gir.',
    signUpDescription:
      'TitanLog deneyimine hazırlanmak için hesap bilgilerini gir.',
    nameLabel: 'Ad Soyad',
    namePlaceholder: 'Adını ve soyadını yaz',
    emailLabel: 'E-posta',
    emailPlaceholder: 'ornek@eposta.com',
    passwordLabel: 'Şifre',
    passwordPlaceholder: 'Şifreni yaz',
    passwordConfirmationLabel: 'Şifre Tekrarı',
    passwordConfirmationPlaceholder: 'Şifreni yeniden yaz',
    forgotPassword: 'Şifremi Unuttum',
    noAccountPrompt: 'Hesabın yok mu? Kayıt Ol',
    existingAccountPrompt: 'Zaten hesabın var mı? Giriş Yap',
    developmentNotice: 'Hesap işlemleri şu anda kullanılamıyor.',
    passwordResetNotice: 'Şifre yenileme şu anda kullanılamıyor.',
    validation: {
      nameRequired: 'Ad soyad alanı zorunludur.',
      emailRequired: 'E-posta alanı zorunludur.',
      passwordRequired: 'Şifre alanı zorunludur.',
      passwordConfirmationRequired: 'Şifre tekrarı alanı zorunludur.',
      passwordMismatch: 'Şifreler eşleşmiyor.',
    },
  },
  home: {
    openProfile: 'Profil ekranını aç',
    welcomeTitle: 'Hoş Geldin',
    welcomeSubtitle:
      'Hedeflerine ulaşmak için antrenmanını planla ve gelişimini takip et.',
    authPrompt: 'Devam etmek için giriş yap veya ücretsiz kayıt ol.',
    todayWorkoutLabel: 'Bugünkü Program',
    startWorkout: 'Antrenmana Başla',
    overviewTitle: 'Genel Bakış',
    sportsDays: 'Spor Günü',
    latestVolume: 'Son Hacim',
    currentWeight: 'Güncel Kilo',
    target: 'Hedef',
    streak: 'Seri',
    dayUnit: 'gün',
    goalTitle: 'Titan Hedefi',
    startingWeight: 'Başlangıç',
    targetWeight: 'Hedef',
    remainingWeight: 'Kalan',
    goalCompleted: 'tamamlandı',
    lastWorkoutTitle: 'Son Antrenman',
    noLastWorkout: 'Henüz tamamlanan antrenman yok.',
    totalVolume: 'Toplam hacim',
    motivationTitle: 'TITAN MODU AKTİF',
    motivationDescription: 'Disiplinini koru, ilerlemeni sahiplen.',
  },
  navigation: {
    home: 'Ana Sayfa',
    workout: 'Antrenman',
    progress: 'Gelişim',
    profile: 'Profil',
    homeAccessibilityLabel: 'Ana Sayfa sekmesi',
    workoutAccessibilityLabel: 'Antrenman sekmesi',
    progressAccessibilityLabel: 'Gelişim sekmesi',
    profileAccessibilityLabel: 'Profil sekmesi',
  },
  workout: {
    title: 'Antrenman',
    activeSession: 'Aktif Antrenman',
    resumeWorkout: 'Antrenmana Devam Et',
    todayWorkout: 'Bugünün Antrenmanı',
    viewProgram: 'Programı Gör',
    startWorkout: 'Antrenmana Başla',
    myProgram: 'Programım',
    editProgram: 'Programı Düzenle',
    programDescription: 'Yerel aktif antrenman programını düzenle.',
    editWorkoutDay: 'Antrenman gününü düzenle',
    dayName: 'Antrenman günü adı',
    dayNamePlaceholder: 'Örneğin Sırt + Biceps',
    dayDescription: 'Açıklama',
    dayDescriptionPlaceholder: 'Kas grubu veya kısa açıklama',
    weekdays: 'Antrenman Günleri',
    saveDay: 'Günü Kaydet',
    daySaved: 'Antrenman günü kaydedildi.',
    invalidDayName: '1–60 karakter arasında bir ad gir.',
    invalidDayDescription: 'Açıklama en fazla 120 karakter olabilir.',
    invalidDaySchedule: 'En az bir antrenman günü seçmelisin.',
    duplicateDayName: 'Bu programda aynı adlı başka bir gün var.',
    scheduleConflict: 'Bu gün başka bir antrenmana atanmış.',
    noScheduledDays: 'Planlanmış gün yok',
    changesNextWorkout: 'Değişiklikler bir sonraki antrenmanda uygulanacak.',
    exercisesTitle: 'Egzersizler',
    editDefaults: 'Varsayılanları Düzenle',
    moveUp: 'Yukarı Taşı',
    moveDown: 'Aşağı Taşı',
    removeFromDay: 'Günden Kaldır',
    removeExerciseTitle: 'Egzersiz günden kaldırılsın mı?',
    removeExerciseDescription:
      'Egzersiz kaydı ve geçmiş oturumlar korunacak. Değişiklik yalnızca gelecekteki antrenmanlara uygulanacak.',
    removeFinalExerciseTitle: 'Son egzersiz kaldırılsın mı?',
    removeFinalExerciseDescription:
      'Bu antrenman gününde egzersiz kalmayacak. Günün kendisi silinmeyecek.',
    removeConfirm: 'Günden Kaldır',
    keepExercise: 'Vazgeç',
    exerciseDefaults: 'Egzersiz Varsayılanları',
    defaultSets: 'Varsayılan set',
    defaultRepetitions: 'Varsayılan tekrar',
    defaultWeight: 'Varsayılan kilo (kg)',
    weightMode: 'Kilo biçimi',
    totalWeight: 'Toplam ağırlık',
    perHandWeight: 'Her el',
    saveDefaults: 'Varsayılanları Kaydet',
    defaultsSaved: 'Egzersiz varsayılanları kaydedildi.',
    invalidDefaultSets: '1 ile 10 arasında tam sayı gir.',
    invalidDefaultRepetitions: '1 ile 100 arasında tam sayı gir.',
    invalidDefaultWeight: '0 ile 2000 kg arasında pozitif bir değer gir.',
    addExercise: 'Egzersiz Ekle',
    addExerciseDescription:
      'Bu güne henüz eklenmemiş yerel egzersizlerden birini seç.',
    searchExercise: 'Egzersiz ara',
    searchExercisePlaceholder: 'Egzersiz adı yaz',
    noAvailableExercises: 'Eklenebilecek egzersiz yok',
    noAvailableExercisesDescription:
      'Yerel egzersizlerin tamamı bu antrenman gününe eklenmiş.',
    noSearchResults: 'Aramayla eşleşen egzersiz bulunamadı.',
    configureExercise: 'Egzersizi Yapılandır',
    addToDay: 'Güne Ekle',
    exerciseAdded: 'Egzersiz antrenman gününe eklendi.',
    duplicateExercise: 'Bu egzersiz antrenman gününde zaten var.',
    createExercise: 'Yeni Egzersiz Oluştur',
    customExerciseTitle: 'Yeni Egzersiz',
    exerciseName: 'Egzersiz adı',
    exerciseNamePlaceholder: 'Örneğin Cable Lateral Raise',
    muscleGroup: 'Kas grubu (isteğe bağlı)',
    muscleGroupPlaceholder: 'Örneğin Omuz',
    equipment: 'Ekipman (isteğe bağlı)',
    equipmentPlaceholder: 'Örneğin Cable machine',
    invalidExerciseName: '1–80 karakter arasında bir egzersiz adı gir.',
    invalidOptionalField: 'Bu alan en fazla 120 karakter olabilir.',
    customExerciseCreated: 'Yeni egzersiz oluşturuldu ve güne eklendi.',
    saveErrorProgram: 'Değişiklik kaydedilemedi. Tekrar dene.',
    reorderError: 'Egzersiz sırası değiştirilemedi.',
    removeError: 'Egzersiz günden kaldırılamadı.',
    discardTitle: 'Kaydedilmemiş değişiklikler silinsin mi?',
    discardDescription: 'Bu ekrandaki değişiklikler kaydedilmedi.',
    discardConfirm: 'Değişiklikleri Sil',
    keepEditing: 'Düzenlemeye Devam Et',
    saving: 'Kaydediliyor…',
    recentWorkouts: 'Son Antrenmanlar',
    historyTitle: 'Antrenman Geçmişi',
    historyDescription: 'Tamamlanan bütün antrenmanların salt okunur kaydı.',
    viewAllHistory: 'Tümünü Gör',
    openWorkoutDetails: 'Antrenman ayrıntılarını aç',
    viewWorkoutDetails: 'Ayrıntıları Gör',
    historyLoading: 'Antrenman geçmişin yükleniyor.',
    historyLoadError: 'Antrenman geçmişine şu anda ulaşılamadı.',
    loadMoreHistory: 'Daha Fazla Yükle',
    detailTitle: 'Antrenman Detayı',
    detailLoading: 'Antrenman ayrıntıları yükleniyor.',
    detailLoadError: 'Antrenman ayrıntılarına şu anda ulaşılamadı.',
    detailNotFound: 'Tamamlanan antrenman bulunamadı',
    detailNotFoundDescription:
      'Bu kayıt geçersiz, tamamlanmamış veya artık kullanılamıyor olabilir.',
    duration: 'Süre',
    comparisonTitle: 'Önceki Aynı Programla Karşılaştırma',
    noComparison: 'Karşılaştırılabilir önceki antrenman yok.',
    previousWorkout: 'Önceki antrenman',
    volumeDifference: 'Hacim farkı',
    setDifference: 'Set farkı',
    repetitionDifference: 'Tekrar farkı',
    durationDifference: 'Süre farkı',
    unavailableComparison: 'Karşılaştırılamıyor',
    unchanged: 'Değişmedi',
    increase: 'artış',
    decrease: 'azalış',
    longer: 'daha uzun',
    shorter: 'daha kısa',
    exerciseBreakdown: 'Egzersiz ve Set Dökümü',
    noCompletedSetsForExercise: 'Bu egzersizde tamamlanan set yok.',
    completedSetStatus: 'Tamamlandı',
    incompleteSetStatus: 'Tamamlanmadı',
    restTitle: 'Bugün dinlenme günü',
    restDescription:
      'Toparlan, enerjini yenile ve bir sonraki antrenmana hazırlan.',
    noHistoryTitle: 'Henüz tamamlanan antrenman yok',
    noHistoryDescription:
      'İlk antrenmanını tamamladığında geçmişin burada görünecek.',
    loading: 'Antrenman verilerin yükleniyor.',
    loadError: 'Antrenman verilerine şu anda ulaşılamadı.',
    retry: 'Tekrar Dene',
    exercises: 'egzersiz',
    sets: 'set',
    repetitions: 'tekrar',
    perHand: 'her el',
    activeSessionNotice: 'Aynı anda yalnızca bir antrenman aktif olabilir.',
    backToActive: 'Aktif Antrenmana Dön',
    dayNotFound: 'Antrenman günü bulunamadı',
    dayNotFoundDescription:
      'Bu program günü kaldırılmış veya geçersiz olabilir.',
    sessionNotFound: 'Antrenman oturumu bulunamadı',
    sessionNotFoundDescription:
      'Bu antrenman kaldırılmış veya artık kullanılamıyor olabilir.',
    startedAt: 'Başlangıç',
    completedSets: 'Tamamlanan Set',
    addSet: 'Set Ekle',
    removeSet: 'Son Seti Kaldır',
    finishWorkout: 'Antrenmanı Bitir',
    cancelWorkout: 'Antrenmanı İptal Et',
    finishTitle: 'Antrenman tamamlansın mı?',
    finishDescription:
      'Tamamlanan setlerin korunacak ve antrenman geçmişine eklenecek.',
    finishConfirm: 'Tamamla',
    cancelTitle: 'Antrenman iptal edilsin mi?',
    cancelDescription:
      'Oturum iptal edilmiş olarak saklanacak ve tamamlanan antrenmanlara sayılmayacak.',
    cancelConfirm: 'İptal Et',
    keepWorkout: 'Vazgeç',
    invalidSet: 'Seti tamamlamak için geçerli kilo ve pozitif tekrar gir.',
    invalidWeight: '0 ile 2000 arasında pozitif bir kilo gir.',
    invalidRepetitions: '0 ile 1000 arasında tam sayı gir.',
    markComplete: 'Tamamla',
    markIncomplete: 'Geri Al',
    weightLabel: 'Kilo (kg)',
    repetitionLabel: 'Tekrar',
    tableExercise: 'Hareket',
    tableSet: 'Set',
    tableWeight: 'Kg',
    tableRepetitions: 'Tk',
    completeSet: 'Seti tamamla',
    completedExercise: 'tamamlandı',
    editSets: 'Setleri düzenle',
    setCompletedAnnouncement: 'Set tamamlandı',
    setEditorTitle: 'Set Ayrıntıları',
    nextSet: 'sıradaki set',
    saveSet: 'Seti Kaydet',
    closeEditor: 'Kapat',
    noCompletedSets: 'Antrenmanı bitirmek için en az bir seti tamamla.',
    writeError: 'Değişiklik kaydedilemedi. Tekrar dene.',
    noExercisesStart:
      'Bu antrenman gününde egzersiz yok. Başlatmadan önce programına egzersiz ekle.',
    noProgramExercisesTitle: 'Bu antrenman gününde egzersiz yok',
    noProgramExercisesDescription:
      'Gelecekte antrenman başlatmak için en az bir egzersiz ekle.',
    completedTitle: 'Antrenman tamamlandı',
    totalRepetitions: 'Toplam Tekrar',
    totalVolume: 'Toplam Hacim',
    completionDescription: 'Emeğin yerel antrenman geçmişine kaydedildi.',
    returnToWorkouts: 'Antrenmanlara Dön',
    exerciseHistoryTitle: 'Egzersiz Geçmişi',
    exerciseHistoryAction: 'Geçmiş',
    exerciseHistoryLoading: 'Egzersiz geçmişi yükleniyor.',
    exerciseHistoryError: 'Egzersiz geçmişine şu anda ulaşılamadı.',
    exerciseHistoryNotFound: 'Egzersiz bulunamadı',
    exerciseHistoryNotFoundDescription:
      'Bu egzersiz kaldırılmış, geçersiz veya güvenle eşleştirilemiyor olabilir.',
    exerciseHistoryEmpty: 'Henüz egzersiz kaydı yok',
    exerciseHistoryEmptyDescription:
      'Bu egzersizi tamamladığın antrenmanlar burada görünecek.',
    recentExerciseRecords: 'Son Kayıtlar',
    highestWeightRecord: 'En Yüksek Ağırlık',
    highestRepetitionRecord: 'En Yüksek Tekrar',
    highestVolumeRecord: 'En Yüksek Hacim',
    highestWeightCompact: 'en yüksek',
    lastExerciseWorkout: 'Son Antrenman',
    legacyExerciseHistoryNote:
      'Bazı eski kayıtlar egzersiz adına göre eşleştirildi.',
    loadMoreExerciseHistory: 'Daha Fazla Göster',
    firstExerciseRecord: 'İlk kayıt',
    previousPerformanceUnavailable: 'Önceki performans yüklenemedi',
    newWeightRecord: 'Yeni ağırlık rekoru',
    newRepetitionRecord: 'Yeni tekrar rekoru',
    newVolumeRecord: 'Yeni hacim rekoru',
  },
  progress: {
    title: 'Gelişim',
    setupTitle: 'Vücut hedefini belirle',
    setupDescription: 'Başlangıç kilonu ve ulaşmak istediğin hedefi kaydet.',
    startingWeight: 'Başlangıç Kilosu',
    targetWeight: 'Hedef Kilo',
    saveGoal: 'Hedefimi Kaydet',
    currentWeight: 'Güncel Kilo',
    start: 'Başlangıç',
    current: 'Güncel',
    target: 'Hedef',
    totalChange: 'Toplam Değişim',
    remaining: 'Hedefe kalan',
    reached: 'Hedefine ulaştın',
    latestChange: 'Son Ölçüm Değişimi',
    noPreviousChange: 'Karşılaştırma için henüz ikinci bir ölçüm yok.',
    addMeasurement: 'Yeni Ölçüm Ekle',
    editGoal: 'Hedefi Düzenle',
    history: 'Ölçüm Geçmişi',
    noExtraMeasurement: 'Henüz ek ölçüm yok',
    noExtraMeasurementDescription:
      'Yeni ölçümler ekledikçe değişimin burada görünecek.',
    editMeasurement: 'Ölçümü Düzenle',
    weight: 'Kilo',
    waist: 'Bel Çevresi',
    chest: 'Göğüs Çevresi',
    upperArm: 'Üst Kol Çevresi',
    hip: 'Kalça Çevresi',
    thigh: 'Uyluk Çevresi',
    note: 'Not',
    notePlaceholder: 'İsteğe bağlı kısa bir not ekle',
    saveMeasurement: 'Ölçümü Kaydet',
    updateMeasurement: 'Değişiklikleri Kaydet',
    deleteMeasurement: 'Ölçümü Sil',
    deleteTitle: 'Ölçüm silinsin mi?',
    deleteDescription: 'Bu işlem geri alınamaz.',
    deleteConfirm: 'Sil',
    onlyMeasurement:
      'Profilin ilk veya tek ölçümü silinemez. Bu kayıt başlangıç değerini korur.',
    invalidWeight: '20 ile 400 kg arasında geçerli bir değer gir.',
    invalidMeasurement: '20 ile 300 cm arasında geçerli bir değer gir.',
    equalGoal: 'Başlangıç ve hedef kilosu farklı olmalıdır.',
    noteTooLong: 'Not en fazla 250 karakter olabilir.',
    saveError: 'Bilgiler kaydedilemedi. Lütfen tekrar dene.',
    loadError: 'Vücut gelişimi verilerine ulaşılamadı.',
    retry: 'Tekrar Dene',
    loading: 'Vücut gelişimi verilerin yükleniyor.',
    measurementNotFound: 'Ölçüm bulunamadı',
    measurementNotFoundDescription:
      'Bu ölçüm kaldırılmış veya geçersiz olabilir.',
    settingsTitle: 'Vücut Hedefi',
    settingsDescription:
      'Bu değerleri değiştirmek geçmiş ilerlemenin yorumunu değiştirebilir.',
    settingsConfirmTitle: 'Hedef güncellensin mi?',
    settingsConfirmDescription:
      'Ölçüm geçmişin korunacak, ilerleme yeni hedefe göre hesaplanacak.',
    updateGoal: 'Hedefi Güncelle',
    setupCtaTitle: 'Vücut hedefini oluştur',
    setupCtaDescription:
      'Kilo gelişimini takip etmek için başlangıç ve hedef değerlerini belirle.',
    setupCtaAction: 'Hedef Belirle',
    kilograms: 'kg',
    centimeters: 'cm',
  },
  profile: {
    title: 'Profil',
    emptyTitle: 'Hesabını oluşturmaya hazır mısın?',
    description:
      'Antrenmanlarını ve gelişimini kişisel hesabınla takip edebileceksin.',
  },
} as const;
