export const appStrings = {
  brandName: 'TitanLog',
  slogan: 'Train. Track. Transform.',
  common: {
    goBack: 'Geri dön',
  },
  database: {
    loadingTitle: 'Antrenman alanın hazırlanıyor',
    loadingDescription: 'Yerel verilerin güvenli biçimde hazırlanıyor.',
    errorTitle: 'Antrenman verilerine ulaşılamadı',
    errorDescription:
      'Yerel veriler hazırlanırken bir sorun oluştu. Tekrar deneyebilirsin.',
    retry: 'Tekrar Dene',
  },
  auth: {
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    signInDescription: 'TitanLog hesabına erişmek için bilgilerini gir.',
    signUpDescription:
      'TitanLog deneyimine hazırlanmak için hesap bilgilerini gir.',
    nameLabel: 'Ad Soyad',
    namePlaceholder: 'Adını ve soyadını yaz',
    emailLabel: 'E-posta',
    emailPlaceholder: 'ornek@eposta.com',
    passwordLabel: 'Şifre',
    passwordPlaceholder: 'Şifreni yaz',
    passwordConfirmationLabel: 'Şifre Tekrarı',
    passwordConfirmationPlaceholder: 'Şifreni yeniden yaz',
    forgotPassword: 'Şifremi Unuttum',
    noAccountPrompt: 'Hesabın yok mu? Kayıt Ol',
    existingAccountPrompt: 'Zaten hesabın var mı? Giriş Yap',
    developmentNotice: 'Hesap işlemleri şu anda kullanılamıyor.',
    passwordResetNotice: 'Şifre yenileme şu anda kullanılamıyor.',
    validation: {
      nameRequired: 'Ad soyad alanı zorunludur.',
      emailRequired: 'E-posta alanı zorunludur.',
      passwordRequired: 'Şifre alanı zorunludur.',
      passwordConfirmationRequired: 'Şifre tekrarı alanı zorunludur.',
      passwordMismatch: 'Şifreler eşleşmiyor.',
    },
  },
  home: {
    openProfile: 'Profil ekranını aç',
    welcomeTitle: 'Hoş Geldin',
    welcomeSubtitle:
      'Hedeflerine ulaşmak için antrenmanını planla ve gelişimini takip et.',
    authPrompt: 'Devam etmek için giriş yap veya ücretsiz kayıt ol.',
    todayWorkoutLabel: 'Bugünkü Program',
    startWorkout: 'Antrenmana Başla',
    overviewTitle: 'Genel Bakış',
    sportsDays: 'Spor Günü',
    currentWeight: 'Güncel Kilo',
    target: 'Hedef',
    streak: 'Seri',
    dayUnit: 'gün',
    goalTitle: 'Titan Hedefi',
    startingWeight: 'Başlangıç',
    targetWeight: 'Hedef',
    remainingWeight: 'Kalan',
    goalCompleted: 'tamamlandı',
    lastWorkoutTitle: 'Son Antrenman',
    totalVolume: 'Toplam hacim',
    motivationTitle: 'TITAN MODU AKTİF',
    motivationDescription: 'Disiplinini koru, ilerlemeni sahiplen.',
  },
  navigation: {
    home: 'Ana Sayfa',
    workout: 'Antrenman',
    progress: 'Gelişim',
    profile: 'Profil',
    homeAccessibilityLabel: 'Ana Sayfa sekmesi',
    workoutAccessibilityLabel: 'Antrenman sekmesi',
    progressAccessibilityLabel: 'Gelişim sekmesi',
    profileAccessibilityLabel: 'Profil sekmesi',
  },
  workout: {
    title: 'Antrenman',
    emptyTitle: 'Program alanın hazırlanıyor',
    description: 'Antrenman planların ve egzersiz kayıtların burada görünecek.',
  },
  progress: {
    title: 'Gelişim',
    emptyTitle: 'Gelişimin görünür olacak',
    description:
      'Kilo, vücut ölçüleri ve antrenman ilerlemen burada özetlenecek.',
  },
  profile: {
    title: 'Profil',
    emptyTitle: 'Hesabını oluşturmaya hazır mısın?',
    description:
      'Antrenmanlarını ve gelişimini kişisel hesabınla takip edebileceksin.',
  },
} as const;
