export const appStrings = {
  brandName: 'TitanLog',
  slogan: 'Train. Track. Transform.',
  common: {
    goBack: 'Geri dön',
  },
  database: {
    loadingTitle: 'Antrenman alanın hazırlanıyor',
    loadingDescription: 'Yerel verilerin güvenli biçimde hazırlanıyor.',
    errorTitle: 'Antrenman verilerine ulaşılamadı',
    errorDescription:
      'Yerel veriler hazırlanırken bir sorun oluştu. Tekrar deneyebilirsin.',
    retry: 'Tekrar Dene',
  },
  auth: {
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    signInDescription: 'TitanLog hesabına erişmek için bilgilerini gir.',
    signUpDescription:
      'TitanLog deneyimine hazırlanmak için hesap bilgilerini gir.',
    nameLabel: 'Ad Soyad',
    namePlaceholder: 'Adını ve soyadını yaz',
    emailLabel: 'E-posta',
    emailPlaceholder: 'ornek@eposta.com',
    passwordLabel: 'Şifre',
    passwordPlaceholder: 'Şifreni yaz',
    passwordConfirmationLabel: 'Şifre Tekrarı',
    passwordConfirmationPlaceholder: 'Şifreni yeniden yaz',
    forgotPassword: 'Şifremi Unuttum',
    noAccountPrompt: 'Hesabın yok mu? Kayıt Ol',
    existingAccountPrompt: 'Zaten hesabın var mı? Giriş Yap',
    developmentNotice: 'Hesap işlemleri şu anda kullanılamıyor.',
    passwordResetNotice: 'Şifre yenileme şu anda kullanılamıyor.',
    validation: {
      nameRequired: 'Ad soyad alanı zorunludur.',
      emailRequired: 'E-posta alanı zorunludur.',
      passwordRequired: 'Şifre alanı zorunludur.',
      passwordConfirmationRequired: 'Şifre tekrarı alanı zorunludur.',
      passwordMismatch: 'Şifreler eşleşmiyor.',
    },
  },
  home: {
    openProfile: 'Profil ekranını aç',
    welcomeTitle: 'Hoş Geldin',
    welcomeSubtitle:
      'Hedeflerine ulaşmak için antrenmanını planla ve gelişimini takip et.',
    authPrompt: 'Devam etmek için giriş yap veya ücretsiz kayıt ol.',
    todayWorkoutLabel: 'Bugünkü Program',
    startWorkout: 'Antrenmana Başla',
    overviewTitle: 'Genel Bakış',
    sportsDays: 'Spor Günü',
    latestVolume: 'Son Hacim',
    currentWeight: 'Güncel Kilo',
    target: 'Hedef',
    streak: 'Seri',
    dayUnit: 'gün',
    goalTitle: 'Titan Hedefi',
    startingWeight: 'Başlangıç',
    targetWeight: 'Hedef',
    remainingWeight: 'Kalan',
    goalCompleted: 'tamamlandı',
    lastWorkoutTitle: 'Son Antrenman',
    noLastWorkout: 'Henüz tamamlanan antrenman yok.',
    totalVolume: 'Toplam hacim',
    motivationTitle: 'TITAN MODU AKTİF',
    motivationDescription: 'Disiplinini koru, ilerlemeni sahiplen.',
  },
  navigation: {
    home: 'Ana Sayfa',
    workout: 'Antrenman',
    progress: 'Gelişim',
    profile: 'Profil',
    homeAccessibilityLabel: 'Ana Sayfa sekmesi',
    workoutAccessibilityLabel: 'Antrenman sekmesi',
    progressAccessibilityLabel: 'Gelişim sekmesi',
    profileAccessibilityLabel: 'Profil sekmesi',
  },
  workout: {
    title: 'Antrenman',
    activeSession: 'Aktif Antrenman',
    resumeWorkout: 'Antrenmana Devam Et',
    todayWorkout: 'Bugünün Antrenmanı',
    viewProgram: 'Programı Gör',
    startWorkout: 'Antrenmana Başla',
    myProgram: 'Programım',
    recentWorkouts: 'Son Antrenmanlar',
    restTitle: 'Bugün dinlenme günü',
    restDescription:
      'Toparlan, enerjini yenile ve bir sonraki antrenmana hazırlan.',
    noHistoryTitle: 'Henüz tamamlanan antrenman yok',
    noHistoryDescription:
      'İlk antrenmanını tamamladığında geçmişin burada görünecek.',
    loading: 'Antrenman verilerin yükleniyor.',
    loadError: 'Antrenman verilerine şu anda ulaşılamadı.',
    retry: 'Tekrar Dene',
    exercises: 'egzersiz',
    sets: 'set',
    repetitions: 'tekrar',
    perHand: 'her el',
    activeSessionNotice: 'Aynı anda yalnızca bir antrenman aktif olabilir.',
    backToActive: 'Aktif Antrenmana Dön',
    dayNotFound: 'Antrenman günü bulunamadı',
    dayNotFoundDescription:
      'Bu program günü kaldırılmış veya geçersiz olabilir.',
    sessionNotFound: 'Antrenman oturumu bulunamadı',
    sessionNotFoundDescription:
      'Bu antrenman kaldırılmış veya artık kullanılamıyor olabilir.',
    startedAt: 'Başlangıç',
    completedSets: 'Tamamlanan Set',
    addSet: 'Set Ekle',
    removeSet: 'Son Seti Kaldır',
    finishWorkout: 'Antrenmanı Bitir',
    cancelWorkout: 'Antrenmanı İptal Et',
    finishTitle: 'Antrenman tamamlansın mı?',
    finishDescription:
      'Tamamlanan setlerin korunacak ve antrenman geçmişine eklenecek.',
    finishConfirm: 'Tamamla',
    cancelTitle: 'Antrenman iptal edilsin mi?',
    cancelDescription:
      'Oturum iptal edilmiş olarak saklanacak ve tamamlanan antrenmanlara sayılmayacak.',
    cancelConfirm: 'İptal Et',
    keepWorkout: 'Vazgeç',
    invalidSet: 'Seti tamamlamak için geçerli kilo ve pozitif tekrar gir.',
    invalidWeight: '0 ile 2000 arasında geçerli bir kilo gir.',
    invalidRepetitions: '0 ile 1000 arasında tam sayı gir.',
    markComplete: 'Tamamla',
    markIncomplete: 'Geri Al',
    weightLabel: 'Kilo (kg)',
    repetitionLabel: 'Tekrar',
    noCompletedSets: 'Antrenmanı bitirmek için en az bir seti tamamla.',
    writeError: 'Değişiklik kaydedilemedi. Tekrar dene.',
    completedTitle: 'Antrenman tamamlandı',
    totalRepetitions: 'Toplam Tekrar',
    totalVolume: 'Toplam Hacim',
    completionDescription: 'Emeğin yerel antrenman geçmişine kaydedildi.',
    returnToWorkouts: 'Antrenmanlara Dön',
  },
  progress: {
    title: 'Gelişim',
    emptyTitle: 'Gelişimin görünür olacak',
    description:
      'Kilo, vücut ölçüleri ve antrenman ilerlemen burada özetlenecek.',
  },
  profile: {
    title: 'Profil',
    emptyTitle: 'Hesabını oluşturmaya hazır mısın?',
    description:
      'Antrenmanlarını ve gelişimini kişisel hesabınla takip edebileceksin.',
  },
} as const;
